name: Build and Test

on:
  pull_request:
    paths:
      - 'src/**'
      - 'build-wasm.sh'
      - 'CMakeLists.txt'
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
      - name: Test
        run: ctest --output-on-failure --test-dir src
        working-directory: build
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.29
          actions-cache-folder: 'emsdk-cache'
      - name: Build Wasm
        run: ./build-wasm.sh
